# Generated by nixos-generate-config for the host named "nixos".  Keep this
# versioned so a rebuild is reproducible; regenerate it only after hardware or
# partition-layout changes, then review and commit the diff.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-f3cbdd6a-3901-4044-85d6-f54f9b4f488c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-f3cbdd6a-3901-4044-85d6-f54f9b4f488c".device =
    "/dev/disk/by-uuid/f3cbdd6a-3901-4044-85d6-f54f9b4f488c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E558-16C7";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-517f231b-27b9-4de9-9942-8f415a04aaea"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
